[package]
name = "pre"
version = "0.1.0"
edition = "2021"

[lib]
name = "pre"
path = "src/lib.rs"

[[bin]]
name = "pre"
path = "src/main.rs"

[dependencies]
toml_edit = "0.24.0"
cargo_toml = "0.22.3"
cfg-expr = "0.20"
